森本さんのPR修正
takahiro619/video_share_app pull request #48
Opened 2023-12-06 06:58 UTC by takahiro619

### 概要
_PR概要を記述する_
bootstrap が反映されていなかったので、修正しました。
### タスク
- [x] なし
- [ ] あり _(タスクのリンクがあれば貼る)_

### 実装内容・手法
_実装内容や、問題の解決手法を記述する_

### 実装画像などあれば添付する

2023-12-07 08:23 UTC, ryusuke-tanaka1 commented on app/controllers/groups_controller.rb
> +  end
このアクションの条件分岐はアクセス権限のためだと思いますが、before_actionを使用したほうが分かりやすいかと思います。

2023-12-07 08:24 UTC, ryusuke-tanaka1 commented on app/controllers/groups_controller.rb
> +  end
ここについてもbefore_actionを使用するのが良いかと思います。

2023-12-07 08:28 UTC, ryusuke-tanaka1 commented on app/views/groups/_form.html.erb
> +    var isInitialized = false;
varではなく、constやletを使用するのが良いかと思います。

2023-12-07 08:31 UTC, ryusuke-tanaka1 commented on spec/system/groups/group_spec.rb
> +    end
新規登録だけでなく、編集の場合のテストも実装すべきだと思います。

2024-03-23 11:56 UTC, takahiro619 commented on app/controllers/groups_controller.rb
> +  end
修正しました。

2024-03-23 11:57 UTC, takahiro619 commented on app/controllers/groups_controller.rb
> +  end
修正しました。

2024-03-23 11:57 UTC, takahiro619 commented on spec/system/groups/group_spec.rb
> +    end
実装しました。

2024-03-23 11:57 UTC, takahiro619 commented on app/views/groups/_form.html.erb
> +    var checkExist = setInterval(function() {
修正しました

2024-03-23 11:58 UTC, takahiro619 commented on app/views/groups/_form.html.erb
> +    var isInitialized = false;
修正しました

2024-07-12 16:02 UTC, ShinichiKikukawa reviewed
一旦、コメントしたのをあげます。

2024-07-15 08:23 UTC, takahiro619 commented on db/migrate/20230312053343_create_groups.rb
> +      t.string :uuid
外部キー系のカラムは、ほとんどbigint で設定されているので、organization_id も bigint にするべきだと思いました。
菊川さんはどのようにお考えでしょうか？

2024-07-15 13:30 UTC, takahiro619 commented on app/controllers/groups_controller.rb
> +  before_action :not_exist, only: %i[show edit update]
ご指摘ありがとうございます。
not_exist の before_action はおそらく退会済みの視聴者をはじくような目的で作成されたと思われます。
また、文法的にもおかしいところがあったので、削除しました。

 def not_exist
    if current_user && Viewer.find_by(id: current_user.id)&.is_valid == false && !current_system_admin?
      flash[:danger] = '存在しないアカウントです。'
      redirect_back(fallback_location: root_url)
    end
  end

代わりにグループの作成画面で.where(is_valid: true) を検索条件に追加して、退会済みの視聴者を選択肢から外すことで代替しました。

def new
    @group = Group.new
    @viewers = Viewer.joins(:organization_viewers)
      .where(organization_viewers: { organization_id: current_user.organization_id })
      .where(is_valid: true)　←追加
  end

2024-07-15 13:59 UTC, takahiro619 commented on app/controllers/groups_controller.rb
> +  # set_viewerが退会済であるページは、システム管理者のみ許可
命名の仕方というのは、こちらの書き方のことでしょうか？　
Group.find_by(uuid: params[:uuid])

2024-07-15 15:27 UTC, ShinichiKikukawa commented on spec/system/groups/group_spec.rb
> +    end
明示的正常異常順Rspec記述法について

以下、テスト結果の見やすさの例
```
# 正常系
グループの新規登録 正常系: 視聴グループが正常に作成される
グループの編集 正常系: 正しい情報を入力すればグループの編集ができる
グループの削除 正常系: 視聴グループの削除に成功する

# 異常系
グループの新規登録 異常系: 視聴グループ名が空の場合、エラーメッセージが表示される
グループの編集 異常系: グループ名を空で更新しようとするとエラーメッセージが表示される
グループの削除 異常系: 無効なグループIDで削除しようとするとエラーメッセージが表示される
```

このように、正常系と異常系を分けて記述することで、どのテストが成功し、どのテストが失敗したかが一目でわかります。

メリット
明示的正常異常順Rspec記述法は、視認性が高く、テスト結果が一目瞭然でエラーの特定が容易になります。さらに、テストがドキュメントとしても機能し、メンテナンスが容易であるため、保守性が向上します。正常系と異常系を明確に分けることで、初学者にも理解しやすくなり、エンジニア全員が同じ基準でテストを書くことでチーム全体の一貫性が保たれ、コードレビューが効率化されます。

デメリット
明示的正常異常順Rspec記述法にはいくつかのデメリットもあります。まず、テストコードが長くなることがありますが、AIの助けを借りることで効率化が可能です。また、共通のテストコードが重複する可能性がありますが、適切なリファクタリングで対策することができます。さらに、テストコードが長くなると、特に大規模なテストスイートでは実行時間が増える可能性があります。

総合評価
総合得点: 90点（メリット 95点 - デメリット 5点）

結論
明示的正常異常順Rspec記述法は、テスト結果の可視性、保守性、デバッグの容易さ、そして初学者にとっての理解のしやすさを大幅に向上させるため、特に大規模プロジェクトやチーム開発において非常に有効です。冗長性やテストの重複、パフォーマンスの問題があるものの、これらは適切な対策を講じることで緩和できます。特に、冗長性に関してはAIの助けを借りることで効率化が可能です。ぜひ、この方法を取り入れてみてください。

```ruby
# spec/system/groups_spec.rb
require 'rails_helper'

RSpec.describe 'グループ管理', type: :system do
  let!(:organization) { create(:organization) }
  let!(:system_admin) { create(:system_admin, confirmed_at: Time.now) }
  let!(:user_staff) { create(:user_staff, confirmed_at: Time.now) }
  let!(:user_owner) { create(:user_owner, confirmed_at: Time.now) }
  let!(:viewer) { create(:viewer) }
  let!(:viewer1) { create(:viewer1) }
  let!(:organization_viewer) { create(:organization_viewer) }
  let!(:organization_viewer2) { create(:organization_viewer2) }

  describe '正常系' do
    describe 'グループの新規登録' do
      let(:current_user) { user_owner }

      before(:each) do
        sign_in(current_user)
        visit new_group_path
      end

      it '正常系: 視聴グループが正常に作成される' do
        fill_in 'group[name]', with: 'Group Name'
        expect(page).to have_select('viewer-select', options: [organization_viewer.viewer.name, organization_viewer2.viewer.name])
        select organization_viewer.viewer.name, from: 'viewer-select'
        expect { find('input[name="commit"]').click }.to change(Group, :count).by(1)
        expect(page).to have_current_path groups_path, ignore_query: true
      end
    end

    describe 'グループの編集' do
      context 'オーナーでログイン' do
        before(:each) do
          sign_in(user_owner)
          visit new_group_path
          fill_in 'group[name]', with: 'New Group Name'
          find('input[name="commit"]').click
          visit groups_path
        end

        it '正常系: 正しい情報を入力すればグループの編集ができて一覧画面に移動する' do
          group = Group.find_by(name: 'New Group Name')
          visit edit_group_path(group.uuid)
          fill_in 'group[name]', with: 'Edited Group Name'
          find('input[name="commit"]').click
          expect(page).to have_current_path groups_path, ignore_query: true
          expect(page).to have_content('Edited Group Name')
        end
      end

      context '管理者でログイン' do
        let!(:group) { create(:group) }

        before(:each) do
          sign_in(system_admin)
          visit edit_group_path(group.uuid)
        end

        it '正常系: 正しい情報を入力すればグループの編集ができて一覧画面に移動する' do
          fill_in 'group[name]', with: 'Edited Group Name'
          find('input[name="commit"]').click
          expect(page).to have_current_path groups_path, ignore_query: true
          expect(page).to havecontent('Edited Group Name')
        end
      end
    end

    describe 'グループの削除' do
      let!(:group) { create(:group, organization_id: user_owner.organization_id) }

      before(:each) do
        sign_in(user_owner)
        visit groups_path
      end

      it '正常系: 視聴グループの削除に成功する' do
        expect(page).to havecontent(group.name)
        find_link('削除', href: group_path(group.uuid)).click
        page.driver.browser.switch_to.alert.accept
        expect(page).to havecontent('グループを削除しました')
        expect(page).to havecurrent_path(groups_path, ignore_query: true)
        expect(Group.count).to eq 0
      end
    end
  end

  describe '異常系' do
    describe 'グループの新規登録' do
      let(:current_user) { user_owner }

      before(:each) do
        sign_in(current_user)
        visit new_group_path
      end

      it '異常系: 視聴グループ名が空の場合、エラーメッセージが表示される' do
        fill_in 'group[name]', with: ''
        find('input[name="commit"]').click
        expect(page).to havecurrent_path groups_path
        expect(page).to havecontent('視聴グループ名を入力してください')
      end
    end

    describe 'グループの編集' do
      context 'オーナーでログイン' do
        before(:each) do
          sign_in(user_owner)
          visit new_group_path
          fill_in 'group[name]', with: 'New Group Name'
          find('input[name="commit"]').click
          visit groups_path
        end

        it '異常系: グループ名を空で更新しようとするとエラーメッセージが表示される' do
          group = Group.find_by(name: 'New Group Name')
          visit edit_group_path(group.uuid)
          fill_in 'group[name]', with: ''
          find('input[name="commit"]').click
          expect(page).to havecurrent_path(edit_group_path(group.uuid, organization_id: group.organization_id))
          expect(page).to havecontent('視聴グループ名を入力してください')
        end
      end

      context '管理者でログイン' do
        let!(:group) { create(:group) }

        before(:each) do
          sign_in(system_admin)
          visit edit_group_path(group.uuid)
        end

        it '異常系: グループ名を空で更新しようとするとエラーメッセージが表示される' do
          fill_in 'group[name]', with: ''
          find('input[name="commit"]').click
          expect(page).to havecurrent_path(edit_group_path(group.uuid, organization_id: group.organization_id))
          expect(page).to havecontent('視聴グループ名を入力してください')
        end
      end
    end

    describe 'グループの削除' do
      let!(:group) { create(:group, organization_id: user_staff.organization_id) }

      before(:each) do
        sign_in(user_staff)
        visit groups_path
      end

      it '異常系: 投稿者でログインしている場合、視聴グループの削除に失敗する' do
        expect(page).to havecontent(group.name)
        find_link('削除', href: group_path(group.uuid)).click
        page.driver.browser.switch_to.alert.accept
        expect(page).to havecontent('権限がありません')
        expect(page).to havecurrent_path(groups_path, ignore_query: true)
        expect(Group.count).to eq 1
      end

      it '異常系: 無効なグループIDで削除しようとするとエラーメッセージが表示される' do
        visit group_path('invalid_uuid')
        expect(page).to havecontent('グループが見つかりません')
        expect(Group.count).to eq 1
      end
    end
  end
end
```

2024-07-15 16:17 UTC, ShinichiKikukawa commented on spec/system/groups/group_spec.rb
> +    end
実機テストしました。動作は良さそうです。

2024-07-16 08:39 UTC, takahiro619 commented on db/migrate/20230312053343_create_groups.rb
> +      t.string :uuid
ありがとうございます。
bigint に修正します。

2024-07-16 12:14 UTC, ShinichiKikukawa requested changes
コメントしたので確認お願いします。

2024-07-18 15:51 UTC, ShinichiKikukawa reviewed
コメント追加しました。DRY関係でコメントがありますが、別タスクで、リファクタリングしてもいいかもしれません。

2024-07-18 15:51 UTC, ShinichiKikukawa commented on app/controllers/groups_controller.rb
> +
発行されるSQLはこんな感じですね。
SELECT "viewers".* FROM "viewers"
INNER JOIN "organization_viewers" ON "organization_viewers"."viewer_id" = "viewers"."id"
WHERE "organization_viewers"."organization_id" = 1
  AND "viewers"."is_valid" = TRUE

このコードは、新しいグループを作成する際に、現在のユーザーが所属する組織内で有効な`Viewer`レコードを取得しています。具体的には、`is_valid`が`true`のユーザーのみを対象とすることで、退会済みのユーザーが含まれないようにしています。これにより、グループメンバーが適切に管理されようですね。

2024-07-18 15:51 UTC, ShinichiKikukawa commented on app/controllers/groups_controller.rb
> +  end
ここは、同じ処理が記述されているので、DRYの原則に従い、modelにメソッドを作って、コントローラはスキニーにしたら、捕手しやすくなりますね。その上で、model＿specを書く、などすれば、スキニーコントローラ、ファットモデル、の原則に沿うので、ベストかと。

具体的な実装
1. モデルにメソッドを追加
```ruby
# app/models/viewer.rb

class Viewer < ApplicationRecord
  # 現在のユーザーまたは指定された組織の有効なViewersを取得するメソッド
  def self.for_organization(organization_id)
    joins(:organization_viewers)
      .where(organization_viewers: { organization_id: organization_id })
      .where(is_valid: true)
  end

  # 管理者かどうかに応じて適切なViewersを取得するメソッド
  def self.for_current_user(user, organization_id_param)
    if user.system_admin?
      for_organization(organization_id_param)
    else
      for_organization(user.organization_id)
    end
  end
end
```
2. コントローラーでモデルのメソッドを呼び出す
```ruby
# app/controllers/groups_controller.rb

def new
  @group = Group.new
  @viewers = Viewer.for_current_user(current_user, params[:organization_id])
end

def edit
  @viewers = Viewer.for_current_user(current_user, params[:organization_id])
end
```

2024-07-18 16:20 UTC, ShinichiKikukawa reviewed
気づいたことをコメントしました。

2024-07-18 16:20 UTC, ShinichiKikukawa commented on app/javascript/stylesheets/groups.scss
> +.center-message {
/* app/assets/stylesheets/groups.css */
これはパス違いません？アセットパイプラインではなく、webpackerで管理しているはずです。

あと、相対パスのファイルパスを明示的にコメントするなら、最上部の方が良いと自分は思います。好みの問題です。

2024-07-18 16:20 UTC, ShinichiKikukawa commented on app/models/video.rb
個人的には、この設計は好きではありません。なんのgroupか、一目瞭然化していないですし。

2024-07-18 16:20 UTC, ShinichiKikukawa commented on app/models/viewer.rb
>    # :lockable, :timeoutable, :trackable and :omniauthable
自分としては、モデルには、先ほどのビジネスロジックのメソッドを追加して、モデルで、できることはモデルでやる方向性に慣れておいた方が良いと考えます。なんでもコントローラに書きたがる、誰も指摘しない悪しき伝統とは訣別できたら良いですね。その上で、正常系、以上系もモデルスペック書けば、現場に近いセンスの品質になっていくのでは?そちらの方向性でいく方がいい、と考えます。

2024-07-18 16:20 UTC, ShinichiKikukawa commented on bin/test
>  # テストの実行
docker-compose run --rm app bin/rails db:migrate RAILS_ENV=test、、、ここ、この記述をする蓋然性と必要性をお教えいただけますか？マイグレートしなければいけない理由をお教えください。

2024-07-18 16:20 UTC, ShinichiKikukawa commented on db/migrate/20230312053343_create_groups.rb
> +      t.string :uuid
.integer :organization_id、、、bigint問題ですね。bigintの方が良いのでは？

2024-07-18 16:23 UTC, ShinichiKikukawa commented on app/controllers/groups_controller.rb
> +  before_action :not_exist, only: %i[show edit update]
not_何ちゃら、、、というメソッド名は自分も痛い目にあったので、以後、当プロジェクトでは避けましょう。

2024-07-18 16:27 UTC, ShinichiKikukawa commented on app/controllers/groups_controller.rb
> +    end
ここは、同じ処理が記述されているので、DRYの原則に従い、modelにメソッドを作って、コントローラはスキニーにしたら、保守しやすくなりますね。その上で、model＿specを書く、などすれば、スキニーコントローラ、ファットモデル、の原則に沿うので、ベストかと。

具体的な実装

モデルにメソッドを追加

```ruby
# app/models/viewer.rb

class Viewer < ApplicationRecord
  # 現在のユーザーまたは指定された組織の有効なViewersを取得するメソッド
  def self.for_organization(organization_id)
    joins(:organization_viewers)
      .where(organization_viewers: { organization_id: organization_id })
      .where(is_valid: true)
  end

  # 管理者かどうかに応じて適切なViewersを取得するメソッド
  def self.for_current_user(user, organization_id_param)
    if user.system_admin?
      for_organization(organization_id_param)
    else
      for_organization(user.organization_id)
    end
  end
end
```

コントローラーでモデルのメソッドを呼び出す

```ruby
# app/controllers/groups_controller.rb

def new
  @group = Group.new
  @viewers = Viewer.for_current_user(current_user, params[:organization_id])
end

def edit
  @viewers = Viewer.for_current_user(current_user, params[:organization_id])
end
```

2024-07-19 20:46 UTC, takahiro619 commented on app/controllers/groups_controller.rb
> +  before_action :not_exist, only: %i[show edit update]
ありがとうございます。勉強になりました。

2024-07-20 01:14 UTC, takahiro619 commented on bin/test
>  # テストの実行
以前、テスト環境でマイグレーションが実行されなかったことがあり、今回も同じケースだったため、
docker-compose run --rm app bin/rails db:migrate RAILS_ENV=test
を記載しました。
こちらは自分でメモとして残しておいたものです。詳しくはこちらを確認してください。
https://github.com/users/takahiro619/projects/2/views/1?pane=issue&itemId=71622320

2024-07-20 13:12 UTC, takahiro619 commented on app/controllers/groups_controller.rb
> +    end
かしこまりました。修正します

2024-07-22 03:04 UTC, takahiro619 commented on app/models/viewer.rb
>    # :lockable, :timeoutable, :trackable and :omniauthable
了解しました。
修正します。

2024-07-22 10:47 UTC, takahiro619 commented on db/migrate/20230312053343_create_groups.rb
> +      t.string :uuid
こちらで bigint に変更しました。
db/migrate/20240717090753_change_organization_id_to_bigint_in_groups.rb
``` ruby
class ChangeOrganizationIdToBigintInGroups < ActiveRecord::Migration[6.0]
  def up
    change_column :groups, :organization_id, :bigint
  end

  def down
    change_column :groups, :organization_id, :integer
  end
end
```

2024-07-24 07:01 UTC, takahiro619 commented on app/javascript/stylesheets/groups.scss
> +.center-message {
不要なコメントを削除しました

2024-07-26 05:19 UTC, takahiro619 commented on app/models/video.rb
group_videos は groupモデルとvideo モデルの中間テーブルだと思われます。

同じように viewer モデルと group モデルの中間テーブルで viewer_group.rb というファイルがあります。
なので個人的にはこれで問題ないかと思いました。

2024-07-26 07:59 UTC, takahiro619 commented on app/controllers/videos_controller.rb
> -      session[:organization_id] = params[:organization_id]
とくに消す必要性は無いと思いますので、戻しました

2024-07-27 10:41 UTC, takahiro619 commented on app/controllers/groups_controller.rb
> +    end
models/viewer.rb　にこのようにメソッドとしてまとめました。

  # 管理者かどうかに応じて適切なViewersを取得するメソッド
  def self.for_current_user(user, _organization_id_param)
    current_owner_has(user).subscribed
  end

  def self.for_system_admin(organization_id_param)
    viewer_has(organization_id_param).subscribed
  end

2024-07-29 15:12 UTC, ShinichiKikukawa commented on app/models/video.rb
group_videos の日本語訳:

「グループビデオ」
「グループ動画」
viewer_groups の日本語訳:

「ビューワーグループ」
「視聴者グループ」
とのこと、group_videos と viewer_groups の両方が、「主体_関連対象」という命名規則に従っているので、一貫性があると判断できると思いますので、OKです。

2024-07-29 16:06 UTC, ShinichiKikukawa commented on app/controllers/groups_controller.rb
> +    end
理解しました。ありがとうございます。

2024-07-29 16:07 UTC, ShinichiKikukawa approved these changes
承認します！お疲れ様でした！

2024-07-30 03:42 UTC, merged